### ISSUE TITLE
Can't authenticate into the SudoSpawner hub

### ISSUE THREAD

**Issue by harschware** [jupyterhub/jupyterhub-example-kerberos#6]
When I attempt to use sudospawner at http://localhost:8001, I get to the spawner options page and enter the password for the alice user 'alice'.  I get the error below.  Should I be entering "alice" in this form?  sorry new to kerberos and fumbling through...

```
hubsudo_1  | [E 2017-09-26 16:56:45.273 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f2a602d52e8> after timeout
hubsudo_1  |     Traceback (most recent call last):
hubsudo_1  |       File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 910, in error_callback
hubsudo_1  |         future.result()
hubsudo_1  |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 294, in spawn
hubsudo_1  |         raise e
hubsudo_1  |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 270, in spawn
hubsudo_1  |         yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
hubsudo_1  |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 108, in wait_up
hubsudo_1  |         yield wait_for_http_server(self.url, timeout=timeout)
hubsudo_1  |       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
hubsudo_1  |         **locals()
hubsudo_1  |     TimeoutError: Server at http://127.0.0.1:33603/user/alice didn't respond in 30 seconds
hubsudo_1  |     
```

**Comment by parente** [comment]
Was this erroring occurring before you pinned versions? For the record, you should be entering username: alice, password: alice as you said.

**Comment by harschware** [comment]
no, it occurred after.. I do recall my system was just a bit slow at the time.  I retested just now and the error no longer occurs.  I've noticed that, even with my 2016 Macbook Pro in fairly idle state authenticating into the hubsudo_1 takes on the order of about 20 seconds.  I'm thinking that at the time because my system was limping a little that I just was legitimately hitting the 30 second timeout.   Is that a configurable parameter?  I wonder why the authentication process is slow?
